http:
  port: "8081"
  
sfdc:
  username: "jchundi@open-logix.com"
  password: "Jithu@2500"
  token: "Eau7ypLI2UsdoGmjk9OK9p66U"
  
file:
  accountsDir: "C:/users/ADMIN/Desktop/APDevFundamentals4.4_studentFiles_SP_23nov2022/resources"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"